collections:
  staff:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "staff"
    values:
      layout: "staff"
  - scope:
      path: ""
    values:
      layout: "base"